src/quotable/urls.py
from django.conf.urls import url
from django.contrib import admin

from quotes.views import (
    Home, 
    QuotesCreate, 
    AddToFavorite, 
    RemoveToFavorite, 
    UserDetails,
    )

from accounts.views import signup, login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home, name='home'),
    url(r'^quotes/$', QuotesCreate.as_view(), name='quotes'),
    url(r'^addtofev/(?P<id>[-\w]+)/$', AddToFavorite, name='add-to-fev'),
    url(r'^remfromfev/(?P<id>[-\w]+)/$', RemoveToFavorite, name='remove-to-fev'),
    url(r'^users/(?P<pk>[-\w]+)/$', UserDetails.as_view(), name='users-details'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$',login_view, name='login'),
    url(r'^logout/$',logout_view, name='logout'),
]

src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
		instance.profile.save()

src/quotes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator


# Create your models here.

class Quote(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	quoted_by = models.CharField(max_length=200, validators=[MinLengthValidator(3,message="More then 3 Charactor")])
	message = models.TextField(validators=[MinLengthValidator(10,message="More then 10 Charactor")])
	

	def __unicode__(self):
		return self.quoted_by

	class Meta:
		ordering = ["-id"]


class FavoriteQuote(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
	is_favorite = models.BooleanField(default=True)

	def __unicode__(self):
		return "%s"%(self.is_favorite)


	class Meta:
		ordering = ["-id"]

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import (authenticate, get_user_model, login, logout)

class SignUpForm(UserCreationForm):
	name = forms.CharField()
	birth_date = forms.DateField()

	class Meta:
		model = User
		fields = ('name','username','email', 'password1', 'password2', 'birth_date' )


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect passsword")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)

src/quotes/forms.py
from django import forms
from .models import Quote



class QuoteForm(forms.ModelForm):
	class Meta:
		model = Quote
		fields = [
			'quoted_by',
			'message',
			]

src/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from .forms import SignUpForm, UserLoginForm
from django.shortcuts import render, redirect
# Create your views here.


def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()  # load the profile instance created by the signal
			user.profile.birth_date = form.cleaned_data.get('birth_date')
			user.save()
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=user.username, password=raw_password)
			login(request, user)
			return redirect('quotes')
	else:
		form = SignUpForm()
	return render(request, 'signup.html', {'form': form})


def login_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect("quotes")
    context = {
        "form": form,
    }
    return render(request, "login.html", context)


def logout_view(request):
	logout(request)
	return redirect("/")

src/quotes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from .forms import QuoteForm
from .models import Quote, FavoriteQuote
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate


from accounts.forms import SignUpForm, UserLoginForm

# Create your views here.

def Home(request):
	if request.user.is_authenticated:
		return redirect('quotes')
	context = {
	"login": UserLoginForm(),
	"reg": SignUpForm(),
	"title":"Login/Registration"
	}
	return render(request, "home.html", context)


class QuotesCreate(CreateView):
	form_class = QuoteForm
	template_name = 'quotes.html'
	success_url = "/quotes/"

	def form_valid(self, form, *args, **kwargs):
		form.instance.user = self.request.user
		return super(QuotesCreate, self).form_valid(form, *args, **kwargs)


	def get_context_data(self, *args, **kwargs):
		context = super(QuotesCreate, self).get_context_data(*args, **kwargs)
		fev_item = []
		quotes_fev = FavoriteQuote.objects.filter(user=self.request.user, is_favorite=True)
		for item in quotes_fev:
			fev_item.append(item.quote.id)
		quotes = Quote.objects.exclude(id__in=fev_item)
		context['title'] = "Quotes"
		context['quotes'] = quotes
		context['quotes_fev'] = quotes_fev

		
		return context


def AddToFavorite(request, id=None):
	quote = Quote.objects.get(id=id)
	FavoriteQuote.objects.create(user=request.user, quote=quote, is_favorite=True)
	return HttpResponseRedirect(reverse("quotes"))


def RemoveToFavorite(request, id=None):
	quote = FavoriteQuote.objects.get(quote__id=id, is_favorite=True)
	quote.is_favorite=False
	quote.save()
	return HttpResponseRedirect(reverse("quotes"))


class UserDetails(DetailView):
	model = User
	template_name = 'user-details.html'

	def get_context_data(self, *args, **kwargs):
		context = super(UserDetails, self).get_context_data(*args, **kwargs)
		context['user_quotes'] = Quote.objects.filter(user__id=self.kwargs['pk'])
		context['userinfo'] = User.objects.get(id=self.kwargs['pk'])
		return context

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>{{ title }}</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#id_birth_date" ).datepicker({
      showOn: "button",
      dateFormat: "yy-mm-dd",
      buttonImage: "https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678116-calendar-20.png",
      buttonImageOnly: true,
      buttonText: "Select date"
    });
  } );
  </script>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="reg" style="width: 400px; margin-left: 250px;float: left;">
	<form method="POST" action="{% url 'signup' %}">{% csrf_token %}
<fieldset>
	  <legend>Register:</legend>

	     
       <p> Name : <input type="text" name="name" required id="id_name" /></p>
        <p>Alias: <input type="text" name="username" autofocus required id="id_username" maxlength="150" /></p>
         <p>Email address: <input type="email" name="email" id="id_email" maxlength="254"  required/></p>
         <p>Password: <input type="password" name="password1" required id="id_password1" />
         </p><small>*password should be at least 8 characters.</small>
        
        <p> Confirm PW: <input type="password" name="password2" required id="id_password2" /></p>
        
        <p>Date of Birth: <input type="text" name="birth_date" required id="id_birth_date" /></p>
       
	 <input value="Register" type="submit">

	 </fieldset>
	</form>
</div>

<div class="log" style="width: 300px; float: right; margin-right: 350px">
	<form method="POST" action="{% url 'login' %}">{% csrf_token %}
	 <fieldset>
	  <legend>Login:</legend>
	 {{ login.as_p }}
	 <input value="Login" type="submit">
	 </fieldset>
	</form>
</div>

{% endblock %}

src/templates/login.html
{% extends "base.html" %}
{% block content %}
      <form method='POST' action='' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
          <div class="form-group">
            <input type='submit' class='btn btn-primary' value='Login' />
          </div>
      </form>
{% endblock content %}

src/templates/quotes.html
{% extends "base.html" %}
{% block content %}
<div class="main">
	<a style="float:right;" href="{% url 'logout' %}">Logout</a>
	<h3>Welcome {{ request.user }}</h3>
	<p>Quotable Quote</p>
	<div class="qarea">
		<div class="quotable">
			{% for qu in quotes %}
			<div class="quote">
				<p><span>{{ qu.quoted_by }} : {{ qu.message }}</span></p>
				<div class="quote-action">
					<small>Posted by : </small><a href="{% url 'users-details' qu.user.id %}"><small>{{ qu.user }}</small></a>
					<a class="fev" href="{% url 'add-to-fev' qu.id %}">Add to My List</a>
				</div>
			</div>
			{% endfor %}
		</div>

 <fieldset class="quotablefev" ">
  <legend>Your Favorites</legend>
			{% for qfev in quotes_fev %}
			<div class="quote">
				<p><span>{{ qfev.quote.quoted_by }} : {{ qfev.quote.message }}</span></p>
				<div class="quote-action">
					<small>Posted by : </small><a href=""><small>{{ qfev.quote.user }}</small></a>
					<a class="fev" href="{% url 'remove-to-fev' qfev.quote.id %}">Remove to My List</a>
				</div>
			</div>
			{% endfor %}
</fieldset>

<div class="quote-create" style="width: 400px;float: right; margin-right: 200px;margin-top: 20px;">
	<p style="margin-left: 0px;">Contribuet a Quote</p>
	<hr>
<form method="POST" action="{% url 'quotes' %}">{% csrf_token %}

	{{ form.as_p }}
		<input style="float: right;margin-right: 73px;margin-top: 14px;" value="SUBMIT" type="submit">
		</form>
</div>

</div>
</div>

{% endblock %}

src/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

src/templates/user-details.html
{% extends "base.html" %}
{% block content %}
<div class="user-data">
	<p>Posted By {{ userinfo }}</p>
	<p>Count : {{ user_quotes.count }}</p>
	<div class="user-action" style="float: right; margin-right: 100px;margin-top: -40px;">
	<a href="{% url 'quotes' %}">Dashboard</a>
	<a>|</a>
	<a href="{% url 'logout' %}">Logout</a>
	</div>

<br>
<div class="quotes" style="width:700px;">
	{% for qt in user_quotes %}
<p><span style="color: red;">{{ qt.quoted_by }} :</span> {{ qt.message }}</p>
{% endfor %}
</div>
</div>
{% endblock %}