assignment/apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login_reg$', views.login_reg, name='login_reg'),
    url(r'^logout$', views.logout, name='logout'),
]

assignment/apps/travel_buddy/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^planner$', views.planner, name='planner'),
    url(r'^show_trip/(?P<id>\d+)$', views.show_trip, name='show_trip'),
    url(r'^add_trip$', views.add_trip, name='add_trip'),
    url(r'^join_trip/(?P<id>\d+)$', views.join_trip, name='join_trip'),
    url(r'^logout$', views.logout, name='logout')
]

assignment/assignment/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^travel_buddy/', include('apps.travel_buddy.urls', namespace='travel_buddy')),
]

assignment/apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
import bcrypt

class UserManager(models.Manager):
    def validate_reg(self, request):
        errors = self.validate_inputs(request)

        if errors:
            return (False, errors)

        pw_hash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

        user = self.create(name=request.POST['name'], username=request.POST['username'], password=pw_hash)

        return (True, user)

    def validate_login(self, request):
        try:
            user = User.objects.get(username=request.POST['username'])
            password = request.POST['password'].encode()
            if bcrypt.checkpw(password, user.password.encode()):
                return (True, user)

        except ObjectDoesNotExist:
            pass

        return (False, ["Invalid login."])

    def validate_inputs(self, request):
        errors = []

        if not request.POST['name']:
            errors.append('First name cannot be blank.')
        elif len(request.POST['name']) < 3:
            errors.append('Name must be more than 3 characters.')
        if not request.POST['username']:
            errors.append('Please enter a username.')
        if len(request.POST['password']) < 8:
            errors.append('Password must be at least 8 characters.')
        if request.POST['password'] != request.POST['confirm']:
            errors.append('Password and password confirm must match.')

        return errors

class User(models.Model):
    name = models.CharField(max_length = 50)
    username = models.CharField(max_length = 50)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

assignment/apps/travel_buddy/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models
from datetime import date, datetime
from dateutil.parser import parse as parse_date

class TripManager(models.Manager):
    def add_trip(self, request):
        errors = self.trip_validations(request)

        if errors:
            return errors

        user = User.objects.get(id=request.session['user']['user_id'])

        Trip.objects.create(destination=request.POST['destination'], description=request.POST['description'], start_date=request.POST['start_date'], end_date=request.POST['end_date'], planner=user)

        return errors

    def join_trip(self, request, id):
        user = User.objects.get(id=request.session['user']['user_id'])

        trip = Trip.objects.get(id=id)

        trip.travelers.add(user)

    def trip_validations(self, request):
        errors = []
        
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']

        if start_date:
            start_date = parse_date(start_date).date()
            if start_date < date.today():
                errors.append('Start date must be today or in the future.')
        else:
            errors.append('Please add a start date.')

        if end_date:
            end_date = parse_date(end_date).date()
            if end_date < date.today():
                errors.append('End date must be today or in the future.')
        else:
            errors.append('Please add an end date.')

        if start_date and end_date:
            if start_date > end_date:
                errors.append('End date must be after or the same as start date.')
            
        if not request.POST['destination']:
            errors.append('Please add a destination.')
        if not request.POST['description']:
            errors.append('Please add a description.')

        return errors

class Trip(models.Model):
    destination = models.CharField(max_length = 50)
    description = models.CharField(max_length = 140)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    planner = models.ForeignKey(User, related_name='trip')
    travelers = models.ManyToManyField(User, related_name='trips')

    objects = TripManager()

assignment/apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import User

def session_check(request):
    if 'user' in request.session:
        return True
    else:
        return False

def index(request):
    if session_check(request):
        return redirect('travel_buddy:index')
        # ^^ REDIRECT TO APP ^^
    else:
        return render(request,'login/index.html')

def login_reg(request):
    if request.POST['action'] == 'register':
        result = User.objects.validate_reg(request)

    elif request.POST['action'] == 'login':
        result = User.objects.validate_login(request)

    if result[0] == False:
        print_errors(request, result[1])
        return redirect('login:index')

    return log_user_in(request, result[1])

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def log_user_in(request, user):
    request.session['user'] = {
        'user_id': user.id,
        'name': user.name
    }

    return redirect('travel_buddy:index')
    # ^^ REDIRECT TO APP ^^

def logout(request):
    request.session.clear()

    return redirect('login:index')

assignment/apps/travel_buddy/views.py
from django.shortcuts import render, redirect
from .models import Trip, User
from django.contrib import messages

def session_check(request):
    if 'user' in request.session:
        return True
    else:
        return False

def index(request):
    if session_check(request):
        context = {
            'user_trips': Trip.objects.filter(planner__id=request.session['user']['user_id']),
            'joined_trips': Trip.objects.filter(travelers__id=request.session['user']['user_id']),
            'all_trips': Trip.objects.all()
        }
        return render(request, 'travel_buddy/index.html', context)

    return redirect('login:index')

def planner(request):
    if session_check(request):
        return render(request, 'travel_buddy/planner.html')

    return redirect('login:index')

def add_trip(request):
    if session_check(request):
        
        errors = Trip.objects.add_trip(request)

        if errors:
            print_errors(request, errors)
            return redirect('travel_buddy:planner')
        
        return redirect('travel_buddy:index')

    return redirect('login:index')

def show_trip(request, id):
    if session_check(request):
        context = {
            'trip': Trip.objects.get(id=id),
            'attendees': User.objects.filter(trips__id=id)
        }
        return render(request, 'travel_buddy/show_trip.html', context)

    return redirect('login:index')

def join_trip(request, id):
    if session_check(request):
        Trip.objects.join_trip(request, id)
        return redirect('travel_buddy:show_trip', id)

    return redirect('login:index')

def print_errors(request, error_list):
    for error in error_list:
        messages.add_message(request, messages.INFO, error)

def logout(request):
    request.session.clear()

    return redirect('login:index')

assignment/apps/login/templates/login/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>-- Travel Buddy --</title>
    {% load static %}
</head>

<body>
    <div id="wrapper">
        <h1>-- Welcome to Travel Buddy --</h1>
        <h2>Log In</h2>
        <form action="{% url 'login:login_reg' %}" method="post">
            {% csrf_token %}
            <p>Username: <input type="text" name="username"></p>
            <p>Password: <input type="password" name="password"></p>
            <input type="hidden" name="action" value="login">
            <input type="submit" name="submit" value="Log In">
        </form><!-- Login -->
        <h2>Register</h2>
        <form action="{% url 'login:login_reg' %}" method="post">
            {% csrf_token %}
            <p>Name: <input type="text" name="name"></p>
            <p>Username: <input type="text" name="username"></p>
            <p>Password: <input type="password" name="password"></p>
            <p>Confirm Password: <input type="password" name="confirm"></p>
            <input type="hidden" name="action" value="register">
            <input type="submit" name="submit" value="Register">
        </form><!-- Registration -->
        {% if messages %}
            {% for message in messages %}
                <h5>{{ message }}</h5>
            {% endfor %}
       {% endif %}
    </div><!--  /#wrapper -->
</body>

</html>

assignment/apps/login/templates/login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>it worked</h1>
</body>
</html>

assignment/apps/travel_buddy/templates/travel_buddy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>-- Travel Buddy --</title>
</head>
<body>
    <h1>Hello, {{ request.session.user.name }}</h1>
    <a href="{% url 'travel_buddy:logout' %}">Logout</a>
    <h3>Your Trip Schedules: </h3>
    <table>
        <tr>
            <th>Destination</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Plan</th>
        </tr>
        {% for trip in user_trips %}
        <tr>
            <td><a href="{% url 'travel_buddy:show_trip' trip.id %}">{{ trip.destination }}</a></td>
            <td>{{ trip.start_date }}</td>
            <td>{{ trip.end_date }}</td>
            <td>{{ trip.description }}</td>
        </tr>
        {% endfor %}
        {% for trip in joined_trips %}
        <tr>
            <td><a href="{% url 'travel_buddy:show_trip' trip.id %}">{{ trip.destination }}</a></td>
            <td>{{ trip.start_date }}</td>
            <td>{{ trip.end_date }}</td>
            <td>{{ trip.description }}</td>
        </tr>
        {% endfor %}
    </table>
    <h3>Other User's Travel Plans: </h3>
    <table>
        <tr>
            <th>Planner</th>
            <th>Destination</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Actions</th>
        </tr>
        {% for trip in all_trips %}
        <tr>
            <td>{{ trip.planner.name }}</td>
            <td><a href="{% url 'travel_buddy:show_trip' trip.id %}">{{ trip.destination }}</a></td>
            <td>{{ trip.start_date }}</td>
            <td>{{ trip.end_date }}</td>
            {% if request.session.user.user_id != trip.planner.id %}
            <td><a href="{% url 'travel_buddy:join_trip' trip.id %}">Join</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'travel_buddy:planner' %}">Plan A Trip</a></p>
</body>
</html>

assignment/apps/travel_buddy/templates/travel_buddy/planner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>-- TB -- | Planner</title>
</head>
<body>
    <a href="{% url 'travel_buddy:index' %}">Home</a>
    <a href="{% url 'travel_buddy:logout' %}">Logout</a>
    <h2>Trip Planner</h2>
    <form action="{% url 'travel_buddy:add_trip' %}" method="POST">
        {% csrf_token %}
        <p>Destination: <input type="text" name="destination"></p>
        <p>Description: <input type="text" name="description"></p>
        <p>From: <input type="date" name="start_date"></p>
        <p>To: <input type="date" name="end_date"></p>
        <input type="submit" value="Add Trip">
    </form>
    {% if messages %}
        {% for message in messages %}
            <h5>{{ message }}</h5>
        {% endfor %}
    {% endif %}
</body>
</html>

assignment/apps/travel_buddy/templates/travel_buddy/show_trip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>-- TB -- | {{ trip.destination }}</title>
</head>
<body>
    <a href="{% url 'travel_buddy:index' %}">Home</a>
    <a href="{% url 'travel_buddy:logout' %}">Logout</a>
    <h2>{{ trip.destination }}</h2>
    <p>Planned By: {{ trip.planner.name }}</p>
    <p>Description: {{ trip.description }}</p>
    <p>From: {{ trip.start_date }}</p>
    <p>To: {{ trip.end_date }}</p>
    <h2>People Attending This Trip:</h2>
    {% for user in attendees %}
    <p>{{ user.name }}</p>
    {% endfor %}
</body>
</html>